#
# repository of freshly collected observations
freshDir: /var/wombat/fresh/heeler
#
# collection host location
altitude: 321
latitude: 12.34
longitude: 123.45
#site: anderson1
site: development
#site: mobile1
#site: vallejo1
#
#
# file to process
#scanFile: /tmp/iwlist.scan
scanFile: /Users/gsc/Documents/github/mellow-heeler-v2/samples/fef1594a-6360-4fe4-ad1e-dbdf942e3ebf
#
# true, there is a GPS available
gpsEnable: false
#
# stations which inhibit collection
homePlateSsid:
  - 'station1'
  - 'station2'
#
