--
-- Title: daily_score.psql
-- Description: file load history
--
-- crate_name is crateName (from json)
-- epoch_seconds is from timeStamp.epochSeconds
-- file_name is fileName (from json)
-- file_type is from project i.e. heeler_v2
-- host_name is from equipment.hostName
-- load_time is when file was processed
-- mode is collection mode
-- obs_quantity is population of observations in file
-- obs_time is observation time from timeStamp.iso8601
-- site_name is from preamble geoLoc.siteName
--
create table heeler_daily_score (
  id            bigserial    primary key,
  crate_name    varchar(32)  not null,
  host_name     varchar(16)  not null,
  quantity_file integer      not null,
  quantity_obs  integer      not null,
  score_date    date         not null
);

grant select, insert, update, delete on heeler_daily_score to heeler_client;
grant usage, select on sequence heeler_daily_score_id_seq to heeler_client;

create unique index heeler_daily_score on heeler_daily_score(crate_name, host_name, score_date);