--
-- Title: load_log.psql
-- Description: file load history
--
-- crate_name is crateName (from json)
-- epoch_seconds is from timeStamp.epochSeconds
-- file_name is fileName (from json)
-- file_type is from project i.e. heeler_v2
-- host_name is from equipment.hostName
-- load_time is when file was processed
-- obs_quantity is population of observations in file
-- obs_time is observation time from timeStamp.iso8601
-- site_name is from preamble geoLoc.siteName
--
create table heeler_load_log (
  id            bigserial    primary key,
  crate_name    varchar(32)  not null,
  epoch_seconds bigint       not null,
  file_name     varchar(48)  unique not null,
  file_type     varchar(48)  not null,
  host_name     varchar(16)  not null,
  load_time     timestamp    not null default CURRENT_TIMESTAMP,
  obs_quantity  smallint     not null,
  obs_time      timestamp    not null,
  site_name     varchar(48)  not null
);

grant select, insert, update, delete on heeler_load_log to heeler_client;
grant usage, select on sequence heeler_load_log_id_seq to heeler_client;

create unique index heeler_load_log_ndx on heeler_load_log(crate_name, host_name, epoch_seconds);
